version: '3.8'

services:
  backend:
    image: wanderleymp/backend:latest
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_CONNECTION_URI: postgresql://postgres:ffcaa89a3e19bd98e911475c7974309b@10.1.0.2:5432/AgileDB?connection_limit=20
      JWT_SECRET: ffcaa89a3e19bd98e911475c7974309b
    networks:
      - AgileNet
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`api.agilefinance.com.br`)"
        - "traefik.http.services.backend.loadbalancer.server.port=3000"
        - "traefik.http.routers.backend.tls.certresolver=letsencryptresolver"
        - "traefik.docker.network=AgileNet"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.middlewares.corsMiddleware.headers.accessControlAllowOriginList=https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3--5173--d3acb9e1.local-credentialless.webcontainer-api.io"
        - "traefik.http.middlewares.corsMiddleware.headers.accessControlAllowMethods=GET,POST,PUT,DELETE,OPTIONS"
        - "traefik.http.middlewares.corsMiddleware.headers.accessControlAllowHeaders=Content-Type,Authorization"
        - "traefik.http.routers.backend.middlewares=corsMiddleware"

networks:
  AgileNet:
    external: true
