

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agile-backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - AgileNet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agile-backend.rule=Host(`api.agilefinance.com.br`) || Host(`api.agilefinance.com.br`)"
      - "traefik.http.services.agile-backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.agile-backend.entrypoints=websecure"
      - "traefik.http.routers.agile-backend.tls.certresolver=letsencryptresolver"

networks:
  AgileNet:
    external: true
