version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agile-backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - agile_network

networks:
  agile_network:
    external: true
