

services:
  app:
    image: wanderleymp/backend:latest
  deploy:
    replicas: 1
    restart_policy:
      condition: on-failure
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - AgileNet
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`api.agilefinance.com.br`)" ## Dominio da aplicação
        - "traefik.http.services.portainer.loadbalancer.server.port=3000"
        - "traefik.http.routers.portainer.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.portainer.service=backend"
        - "traefik.docker.network=AgileNet" ## Nome da rede interna
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.priority=1"     
networks:
  AgileNet: ## Nome da rede interna
    external: true
    attachable: true
    name: AgileNet ## Nome da rede interna
