version: '3.8'

services:
  agile-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agile-backend
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    networks:
      - agile-network

networks:
  agile-network:
    external: true
