

services:
  app:
    image: wanderleymp/backend:latest
  deploy:
    replicas: 1
    restart_policy:
      condition: on-failure
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - backendNet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agile-backend.rule=Host(`api.agilefinance.com.br`)
      - "traefik.http.services.agile-backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.agile-backend.entrypoints=websecure"
      - traefik.http.services.agile-backend.loadbalancer.passHostHeader=true
      - traefik.http.routers.agile-backend.service=agile-backend
      - "traefik.http.routers.agile-backend.tls.certresolver=letsencryptresolver"
     
networks:
  AgileNet:
    external: true
