version: '3.8'

services:
  api:
    image: wanderleymp/backend:latest
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: localhost
      DB_USER: usuario
      DB_PASS: senha
    ports:
      - "3000:3000"
    networks:
      - AgileNet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.agilefinance.com.br`)"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
      - "traefik.http.routers.api.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.api.service=api"
      - "traefik.docker.network=AgileNet"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.priority=1"

networks:
  AgileNet:
    external: true
    attachable: true
    name: AgileNet
