version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agile-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  agile-network:
    external: true
